const correctPassword = "qorwldn"; // 원하는 비밀번호로 변경 가능



const peopleMBTI = {
  "김가연": "ESTJ",
  "김민준": "INTJ",
  "김은서": "ESFP",
  "김준겸": "ISTJ",
  "김채연": "ESFP",
  "김태호": "ESTP",
  "김현성": "",
  "문지환": "ENTP",
  "신효성": "ENTP",
  "오서연": "ENFJ",
  "유하준": "",
  "윤준하": "",
  "윤지후": "ISFJ",
  "이가영": "ESFP",
  "이단비": "INTJ",
  "이여울": "",
  "이주형": "INFP",
  "전채빈": "ESTP",
  "정지환": "",
  "조유건": "ISTJ",
  "최인준": "ISTP",
  "허예원": "ISFP",
  "황석연": "",
  "고승우": "INFP",
  "고예준": "ESFP",
  "김기범": "ENFP",
  "김서율": "ISFP",
  "김시연": "ESTP/ISFP",
  "김시헌": "INFP",
  "김은채": "ENFP",
  "김재현": "",
  "김지민": "ESTJ",
  "문다빈": "ISTJ",
  "박서연": "ESTP",
  "서찬영": "ENFP",
  "손지선": "ISFP",
  "우태민": "ESFP",
  "유가연": "ISTP",
  "이건우": "ENFP",
  "이단우": "ISTP",
  "이현서": "",
  "임서진": "ENFP",
  "조예성": "ENFP",
  "조은상": "INFP",
  "최혁인": "INFP",
  "공두연": "INTP",
  "곽선후": "INFP",
  "권지유": "ESTJ",
  "김규범": "",
  "김민결": "ENTP",
  "김민우": "ENFP",
  "김예운": "ISTJ",
  "김찬유": "ESTP",
  "박동윤": "INFP",
  "박민호": "ENTJ",
  "박지민": "INTJ/INTP",
  "박지연": "INFP",
  "송현주": "ENTP",
  "윤승재": "ENTP",
  "윤예은": "ISFP",
  "이승기": "ISFJ",
  "이지효": "ISTJ",
  "임라희": "ESFP",
  "전이찬": "ENTP",
  "정우준": "INFP",
  "정지훈": "ISTJ",
  "홍예서": "INFP",
  "강재연": "ENTP",
  "김민재": "ENTP",
  "김송현": "ENFP",
  "김우녹": "ISTP",
  "김지안": "ESFJ",
  "류희재": "ISTP",
  "박정우": "INFJ",
  "박진우": "ISTP",
  "서미소": "INFP",
  "서원빈": "ISTJ",
  "석재우": "ENFP",
  "오현": "ENTP",
  "유수현": "ENFP",
  "이다은": "ESTP",
  "이도윤": "ENTP",
  "이재솔": "ISTP",
  "전지용": "ISFP",
  "정성우": "ENFJ",
  "정예원": "ISFP",
  "지예경": "INFJ",
  "최승우": "ENTJ",
  "하지우": "ENTP",
  "허준혁": "ENFP",
  "김두연": "ESTP",
  "김재아": "ISTP",
  "김용일": "ESTP",
  "김태협": "ENTP",
  "김효재": "ENTP",
  "나윤서": "INFP",
  "박상원": "INTP",
  "박시원": "ISTP",
  "배상혁": "INFP",
  "배지혜": "ENFJ",
  "소은재": "INFJ",
  "유정인": "ENTJ",
  "윤선우": "ESFP",
  "윤정후": "ISTJ",
  "이세상": "ENTP",
  "이시윤": "ISTP",
  "이예안": "ISTP",
  "이윤아": "ENFJ",
  "이지훈": "INTJ",
  "전리안": "ENTP",
  "차정연": "INTJ",
  "차준혁": "ENTP",
  "최꽃님": "INFP",
  "강창우": "ENTP",
  "김세은": "INFP",
  "김주한": "ENFJ",
  "김지유": "ISTP",
  "노제인": "ENTJ",
  "문지원": "INTP",
  "박세준": "INFP",
  "박지우": "INTJ/INFP",
  "서채은": "ISFP",
  "신수호": "ISTP",
  "신이안": "INTP",
  "신현서": "ENFP",
  "안지민": "ENFP",
  "유이안": "ENFP",
  "이강연": "ISTJ",
  "이예찬": "INTP",
  "임영서": "ISTP",
  "정지우": "",
  "조형우": "INTP",
  "천진현": "",
  "최우인": "INFJ",
  "최호윤": "INTJ",
  "권지환": "INFP",
  "김강민": "ENTP",
  "김도현": "ENTP",
  "김태은": "ISTJ",
  "박상우": "INTP",
  "박주형": "ENFP",
  "백지우": "ISFP",
  "설승찬": "ENTP",
  "송지효": "ISTP",
  "안서진": "ENTP",
  "양세현": "ENTJ",
  "여나연": "ISFJ",
  "여은기": "INFP",
  "우혁진": "ISTP",
  "이나경": "ISTP",
  "조수아": "ISTP",
  "조하람": "ISFP",
  "차민서": "ENTP",
  "채은빛": "INFP",
  "최치현": "ENFP",
  "한다윤": "INFP",
  "허나경": "ISTP"
};


function unlock() {
  const input = document.getElementById("passwordInput").value;
  const message = document.getElementById("passwordMessage");

  if (input === correctPassword) {
    document.getElementById("lockScreen").style.display = "none";
    document.getElementById("mainContent").style.display = "block";
  } else {
    message.textContent = "비밀번호가 틀렸습니다.";
  }
}

function checkMBTI() {
  const name = document.getElementById("nameInput").value.trim();
  const result = document.getElementById("result");

  if (peopleMBTI[name]) {
    result.textContent = `${name}의 MBTI: ${peopleMBTI[name]}.`;
  } else {
    result.textContent = `${name}의 MBTI 정보 없음`;
  }
}
